version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://prisma:prisma@db:5432/mydatabase
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  siege:
    build:
      context: ./siege_service
    volumes:
      - ./siege:/siege

volumes:
  postgres_data:
